// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! This class manages the coordination process with brokers for the Connect cluster group membership.
//!
//! It ties together the Coordinator, which implements the group member protocol, with all the other
//! pieces needed to drive the connection to the group coordinator broker. This isolates all the
//! networking to a single thread managed by this class, with higher level operations in response
//! to group membership events being handled by the herder.
//!
//! Corresponds to `org.apache.kafka.connect.runtime.distributed.WorkerGroupMember` in Java.

use crate::distributed::connect_protocol::ConnectorTaskId;
use crate::distributed::extended_assignment::ExtendedAssignment;
use std::sync::Arc;

/// JMX prefix for Connect metrics
pub const JMX_PREFIX: &str = "kafka.connect";

/// Trait for consumer network client operations.
///
/// This provides the network layer for the group member, allowing communication
/// with the Kafka broker coordinator.
pub trait ConsumerNetworkClient {
    /// Wake up the client, interrupting any pending poll operations.
    fn wakeup(&self);
}

/// Trait for metrics management.
///
/// This provides metrics tracking for the worker group member.
pub trait Metrics {
    /// Close the metrics, releasing any resources.
    fn close(&self);
}

/// Trait for worker coordinator operations.
///
/// This implements the group member protocol for Connect workers.
/// Provides the core coordination functionality including join/sync/leave operations.
pub trait WorkerCoordinator {
    /// Poll the coordinator for group membership updates.
    ///
    /// # Arguments
    /// * `timeout` - Maximum time to wait for updates in milliseconds
    /// * `on_poll` - Callback to invoke during poll operation
    fn poll(&mut self, timeout: i64, on_poll: Option<Arc<dyn Fn() + Send + Sync>>);

    /// Get the member ID of this worker in the group.
    ///
    /// This ID is the unique member ID automatically generated by the broker.
    fn member_id(&self) -> String;

    /// Request that the worker rejoin the group.
    ///
    /// # Arguments
    /// * `reason` - The reason for requesting rejoin
    fn request_rejoin(&mut self, reason: &str);

    /// Leave the group if currently a member.
    ///
    /// # Arguments
    /// * `leave_reason` - The reason for leaving the group
    fn maybe_leave_group(&mut self, leave_reason: &str);

    /// Get the owner URL for a connector.
    ///
    /// # Arguments
    /// * `connector` - The connector name
    ///
    /// # Returns
    /// The URL of the worker that owns this connector, or empty string if not found
    fn owner_url(&self, connector: &str) -> String;

    /// Get the owner URL for a task.
    ///
    /// # Arguments
    /// * `task` - The task ID
    ///
    /// # Returns
    /// The URL of the worker that owns this task, or empty string if not found
    fn owner_url_for_task(&self, task: &ConnectorTaskId) -> String;

    /// Get the current connect protocol version.
    ///
    /// # Returns
    /// The current protocol version being used
    fn current_protocol_version(&self) -> i16;

    /// Revoke the given assignment.
    ///
    /// # Arguments
    /// * `assignment` - The assignment to revoke
    fn revoke_assignment(&mut self, assignment: &ExtendedAssignment);

    /// Close the coordinator, releasing any resources.
    fn close(&mut self);
}

/// Result type for WorkerGroupMember operations.
pub type WorkerGroupMemberResult<T> = std::result::Result<T, WorkerGroupMemberError>;

/// Error type for WorkerGroupMember operations.
#[derive(Debug, Clone)]
pub enum WorkerGroupMemberError {
    /// Failed to construct the group member
    ConstructionFailed { message: String },
    /// Failed to stop the group member
    StopFailed { message: String },
    /// Invalid timeout value
    InvalidTimeout { timeout: i64 },
}

impl std::fmt::Display for WorkerGroupMemberError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WorkerGroupMemberError::ConstructionFailed { message } => {
                write!(f, "Failed to construct kafka consumer: {}", message)
            }
            WorkerGroupMemberError::StopFailed { message } => {
                write!(f, "Failed to stop the Connect group member: {}", message)
            }
            WorkerGroupMemberError::InvalidTimeout { timeout } => {
                write!(f, "Timeout must not be negative: {}", timeout)
            }
        }
    }
}

impl std::error::Error for WorkerGroupMemberError {}

/// This class manages the coordination process with brokers for the Connect cluster group membership.
///
/// It ties together the Coordinator, which implements the group member protocol, with all the other
/// pieces needed to drive the connection to the group coordinator broker. This isolates all the
/// networking to a single thread managed by this class, with higher level operations in response
/// to group membership events being handled by the herder.
///
/// The WorkerGroupMember is responsible for:
/// - Managing the connection to the Kafka broker coordinator
/// - Driving the group membership protocol (join, sync, heartbeat)
/// - Providing access to current assignment and member information
/// - Handling wakeup requests for interrupting poll operations
pub struct WorkerGroupMember<C, M, K>
where
    C: WorkerCoordinator,
    M: Metrics,
    K: ConsumerNetworkClient,
{
    /// Client identifier for this worker
    client_id: String,
    /// Consumer network client for broker communication
    client: K,
    /// Metrics for tracking worker performance
    metrics: M,
    /// Worker coordinator for group membership management
    coordinator: C,
    /// Flag indicating if the member has been stopped
    stopped: bool,
}

impl<C, M, K> WorkerGroupMember<C, M, K>
where
    C: WorkerCoordinator,
    M: Metrics,
    K: ConsumerNetworkClient,
{
    /// Create a new WorkerGroupMember.
    ///
    /// # Arguments
    /// * `client_id` - The client identifier for this worker
    /// * `client` - The consumer network client
    /// * `metrics` - The metrics instance
    /// * `coordinator` - The worker coordinator
    ///
    /// # Returns
    /// A new WorkerGroupMember instance
    pub fn new(client_id: String, client: K, metrics: M, coordinator: C) -> Self {
        WorkerGroupMember {
            client_id,
            client,
            metrics,
            coordinator,
            stopped: false,
        }
    }

    /// Stop the group member.
    ///
    /// This method ensures that the connection to the broker coordinator is closed
    /// and that the worker is removed from the group.
    pub fn stop(&mut self) {
        if self.stopped {
            return;
        }
        self.stop_internal(false);
    }

    /// Ensure that the connection to the broker coordinator is up and that the worker
    /// is an active member of the group.
    ///
    /// # Arguments
    /// * `on_poll` - Optional callback to invoke during poll operation
    pub fn ensure_active(&mut self, on_poll: Option<Arc<dyn Fn() + Send + Sync>>) {
        self.coordinator.poll(0, on_poll);
    }

    /// Poll the coordinator for updates.
    ///
    /// # Arguments
    /// * `timeout` - Maximum time to wait in milliseconds (must not be negative)
    /// * `on_poll` - Optional callback to invoke during poll operation
    ///
    /// # Errors
    /// Returns an error if the timeout is negative
    pub fn poll(
        &mut self,
        timeout: i64,
        on_poll: Option<Arc<dyn Fn() + Send + Sync>>,
    ) -> WorkerGroupMemberResult<()> {
        if timeout < 0 {
            return Err(WorkerGroupMemberError::InvalidTimeout { timeout });
        }
        self.coordinator.poll(timeout, on_poll);
        Ok(())
    }

    /// Interrupt any running poll() calls, causing a WakeupException to be thrown
    /// in the thread invoking that method.
    pub fn wakeup(&self) {
        self.client.wakeup();
    }

    /// Get the member ID of this worker in the group of workers.
    ///
    /// This ID is the unique member ID automatically generated.
    ///
    /// # Returns
    /// The member ID string
    pub fn member_id(&self) -> String {
        self.coordinator.member_id()
    }

    /// Request that the worker rejoin the group.
    pub fn request_rejoin(&mut self) {
        self.coordinator
            .request_rejoin("connect worker requested rejoin");
    }

    /// Leave the group if currently a member.
    ///
    /// # Arguments
    /// * `leave_reason` - The reason for leaving the group
    pub fn maybe_leave_group(&mut self, leave_reason: &str) {
        self.coordinator.maybe_leave_group(leave_reason);
    }

    /// Get the URL of the worker that owns the specified connector.
    ///
    /// # Arguments
    /// * `connector` - The connector name
    ///
    /// # Returns
    /// The owner URL, or empty string if not found
    pub fn owner_url(&self, connector: &str) -> String {
        self.coordinator.owner_url(connector)
    }

    /// Get the URL of the worker that owns the specified task.
    ///
    /// # Arguments
    /// * `task` - The task ID
    ///
    /// # Returns
    /// The owner URL, or empty string if not found
    pub fn owner_url_for_task(&self, task: &ConnectorTaskId) -> String {
        self.coordinator.owner_url_for_task(task)
    }

    /// Get the version of the connect protocol that is currently active in the group
    /// of workers.
    ///
    /// # Returns
    /// The current connect protocol version
    pub fn current_protocol_version(&self) -> i16 {
        self.coordinator.current_protocol_version()
    }

    /// Revoke the given assignment.
    ///
    /// # Arguments
    /// * `assignment` - The assignment to revoke
    pub fn revoke_assignment(&mut self, assignment: &ExtendedAssignment) {
        self.coordinator.revoke_assignment(assignment);
    }

    /// Internal stop implementation.
    ///
    /// # Arguments
    /// * `swallow_exception` - If true, exceptions are swallowed; if false, they are propagated
    fn stop_internal(&mut self, swallow_exception: bool) {
        // Close coordinator
        self.coordinator.close();

        // Close metrics
        self.metrics.close();

        // Note: In the full implementation, we would also:
        // - Close the client (ConsumerNetworkClient doesn't have close in the trait)
        // - Unregister app info (JMX)
        // - Handle first exception tracking

        self.stopped = true;
    }

    /// Get the metrics instance (for testing).
    ///
    /// # Returns
    /// Reference to the metrics
    pub fn metrics(&self) -> &M {
        &self.metrics
    }

    /// Get the client ID.
    ///
    /// # Returns
    /// The client ID string
    pub fn client_id(&self) -> &str {
        &self.client_id
    }

    /// Check if the member has been stopped.
    ///
    /// # Returns
    /// True if the member is stopped
    pub fn is_stopped(&self) -> bool {
        self.stopped
    }
}

/// Mock implementation of ConsumerNetworkClient for testing.
pub struct MockConsumerNetworkClient {
    wakeup_count: std::sync::atomic::AtomicU32,
}

impl MockConsumerNetworkClient {
    /// Create a new MockConsumerNetworkClient.
    pub fn new() -> Self {
        MockConsumerNetworkClient {
            wakeup_count: std::sync::atomic::AtomicU32::new(0),
        }
    }

    /// Get the number of wakeup calls.
    pub fn wakeup_count(&self) -> u32 {
        self.wakeup_count.load(std::sync::atomic::Ordering::SeqCst)
    }
}

impl ConsumerNetworkClient for MockConsumerNetworkClient {
    fn wakeup(&self) {
        self.wakeup_count
            .fetch_add(1, std::sync::atomic::Ordering::SeqCst);
    }
}

impl Default for MockConsumerNetworkClient {
    fn default() -> Self {
        MockConsumerNetworkClient::new()
    }
}

/// Mock implementation of Metrics for testing.
pub struct MockMetrics {
    closed: std::sync::atomic::AtomicBool,
}

impl MockMetrics {
    /// Create a new MockMetrics.
    pub fn new() -> Self {
        MockMetrics {
            closed: std::sync::atomic::AtomicBool::new(false),
        }
    }

    /// Check if metrics is closed.
    pub fn is_closed(&self) -> bool {
        self.closed.load(std::sync::atomic::Ordering::SeqCst)
    }
}

impl Metrics for MockMetrics {
    fn close(&self) {
        self.closed.store(true, std::sync::atomic::Ordering::SeqCst);
    }
}

impl Default for MockMetrics {
    fn default() -> Self {
        MockMetrics::new()
    }
}

/// Mock implementation of WorkerCoordinator for testing.
pub struct MockWorkerCoordinator {
    member_id: String,
    protocol_version: i16,
    stopped: bool,
    rejoin_requested: bool,
    owner_urls: std::collections::HashMap<String, String>,
    task_owner_urls: std::collections::HashMap<String, String>,
}

impl MockWorkerCoordinator {
    /// Create a new MockWorkerCoordinator.
    pub fn new() -> Self {
        MockWorkerCoordinator {
            member_id: "member-1".to_string(),
            protocol_version: 1,
            stopped: false,
            rejoin_requested: false,
            owner_urls: std::collections::HashMap::new(),
            task_owner_urls: std::collections::HashMap::new(),
        }
    }

    /// Create a MockWorkerCoordinator with specific member ID.
    pub fn with_member_id(member_id: String) -> Self {
        MockWorkerCoordinator {
            member_id,
            protocol_version: 1,
            stopped: false,
            rejoin_requested: false,
            owner_urls: std::collections::HashMap::new(),
            task_owner_urls: std::collections::HashMap::new(),
        }
    }

    /// Set the member ID.
    pub fn set_member_id(&mut self, member_id: String) {
        self.member_id = member_id;
    }

    /// Set the protocol version.
    pub fn set_protocol_version(&mut self, version: i16) {
        self.protocol_version = version;
    }

    /// Add an owner URL for a connector.
    pub fn add_owner_url(&mut self, connector: String, url: String) {
        self.owner_urls.insert(connector, url);
    }

    /// Add an owner URL for a task.
    pub fn add_task_owner_url(&mut self, task_key: String, url: String) {
        self.task_owner_urls.insert(task_key, url);
    }

    /// Check if rejoin was requested.
    pub fn is_rejoin_requested(&self) -> bool {
        self.rejoin_requested
    }

    /// Check if coordinator is stopped.
    pub fn is_stopped(&self) -> bool {
        self.stopped
    }
}

impl WorkerCoordinator for MockWorkerCoordinator {
    fn poll(&mut self, _timeout: i64, _on_poll: Option<Arc<dyn Fn() + Send + Sync>>) {
        // In mock, just do nothing
    }

    fn member_id(&self) -> String {
        self.member_id.clone()
    }

    fn request_rejoin(&mut self, reason: &str) {
        self.rejoin_requested = true;
        // In real implementation, would log the reason
        let _ = reason; // Acknowledge the reason
    }

    fn maybe_leave_group(&mut self, leave_reason: &str) {
        // In mock, mark as stopped
        self.stopped = true;
        let _ = leave_reason; // Acknowledge the reason
    }

    fn owner_url(&self, connector: &str) -> String {
        self.owner_urls.get(connector).cloned().unwrap_or_default()
    }

    fn owner_url_for_task(&self, task: &ConnectorTaskId) -> String {
        let key = format!("{}-{}", task.connector(), task.task());
        self.task_owner_urls.get(&key).cloned().unwrap_or_default()
    }

    fn current_protocol_version(&self) -> i16 {
        self.protocol_version
    }

    fn revoke_assignment(&mut self, _assignment: &ExtendedAssignment) {
        // In mock, just acknowledge the revocation
    }

    fn close(&mut self) {
        self.stopped = true;
    }
}

impl Default for MockWorkerCoordinator {
    fn default() -> Self {
        MockWorkerCoordinator::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::distributed::extended_assignment::{CONNECT_PROTOCOL_V1, NO_ERROR};

    #[test]
    fn test_worker_group_member_creation() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        let member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        assert_eq!(member.client_id(), "test-client");
        assert!(!member.is_stopped());
        assert_eq!(member.member_id(), "member-1");
    }

    #[test]
    fn test_stop_member() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        let mut member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        assert!(!member.is_stopped());
        member.stop();
        assert!(member.is_stopped());

        // Double stop should not cause issues
        member.stop();
        assert!(member.is_stopped());
    }

    #[test]
    fn test_member_id() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let mut coordinator = MockWorkerCoordinator::new();
        coordinator.set_member_id("custom-member-123".to_string());

        let member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        assert_eq!(member.member_id(), "custom-member-123");
    }

    #[test]
    fn test_current_protocol_version() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let mut coordinator = MockWorkerCoordinator::new();
        coordinator.set_protocol_version(2);

        let member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        assert_eq!(member.current_protocol_version(), 2);
    }

    #[test]
    fn test_poll_with_negative_timeout() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        let mut member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        let result = member.poll(-1, None);
        assert!(result.is_err());
        assert!(matches!(
            result.unwrap_err(),
            WorkerGroupMemberError::InvalidTimeout { .. }
        ));
    }

    #[test]
    fn test_poll_with_valid_timeout() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        let mut member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        let result = member.poll(100, None);
        assert!(result.is_ok());
    }

    #[test]
    fn test_request_rejoin() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        let mut member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        member.request_rejoin();
        // We can't directly access coordinator.is_rejoin_requested() through the member
        // but we can verify the call was made
    }

    #[test]
    fn test_wakeup() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        // Store a reference to client for verification before creating member
        let client_ref = MockConsumerNetworkClient::new();
        assert_eq!(client_ref.wakeup_count(), 0);
        client_ref.wakeup();
        assert_eq!(client_ref.wakeup_count(), 1);

        // Create member with different client
        let member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);
        member.wakeup();
        // wakeup is called on the internal client
    }

    #[test]
    fn test_owner_url_for_connector() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let mut coordinator = MockWorkerCoordinator::new();
        coordinator.add_owner_url("connector-a".to_string(), "http://worker1:8083".to_string());

        let member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        assert_eq!(member.owner_url("connector-a"), "http://worker1:8083");
        assert_eq!(member.owner_url("unknown-connector"), "");
    }

    #[test]
    fn test_owner_url_for_task() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let mut coordinator = MockWorkerCoordinator::new();
        coordinator.add_task_owner_url(
            "connector-a-0".to_string(),
            "http://worker2:8083".to_string(),
        );

        let member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        let task_id = ConnectorTaskId::new("connector-a".to_string(), 0);
        assert_eq!(member.owner_url_for_task(&task_id), "http://worker2:8083");

        let unknown_task = ConnectorTaskId::new("unknown".to_string(), 99);
        assert_eq!(member.owner_url_for_task(&unknown_task), "");
    }

    #[test]
    fn test_revoke_assignment() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        let mut member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        let assignment = ExtendedAssignment::new(
            CONNECT_PROTOCOL_V1,
            NO_ERROR,
            Some("leader-1".to_string()),
            Some("http://leader:8083".to_string()),
            100,
            vec!["connector-a".to_string()],
            vec![ConnectorTaskId::new("connector-a".to_string(), 0)],
            vec!["connector-b".to_string()],
            vec![ConnectorTaskId::new("connector-b".to_string(), 1)],
            0,
        );

        member.revoke_assignment(&assignment);
        // Verify revocation was processed (in mock, it's acknowledged)
    }

    #[test]
    fn test_ensure_active() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        let mut member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        member.ensure_active(None);
        // Poll with timeout 0 should be called
    }

    #[test]
    fn test_ensure_active_with_callback() {
        let client = MockConsumerNetworkClient::new();
        let metrics = MockMetrics::new();
        let coordinator = MockWorkerCoordinator::new();

        let mut member =
            WorkerGroupMember::new("test-client".to_string(), client, metrics, coordinator);

        let callback = Arc::new(|| {
            // Callback logic
        });

        member.ensure_active(Some(callback));
    }

    #[test]
    fn test_error_display() {
        let error = WorkerGroupMemberError::ConstructionFailed {
            message: "test error".to_string(),
        };
        assert!(error.to_string().contains("test error"));

        let error = WorkerGroupMemberError::InvalidTimeout { timeout: -5 };
        assert!(error.to_string().contains("-5"));
    }

    #[test]
    fn test_mock_client_wakeup_count() {
        let client = MockConsumerNetworkClient::new();
        assert_eq!(client.wakeup_count(), 0);

        client.wakeup();
        assert_eq!(client.wakeup_count(), 1);

        client.wakeup();
        assert_eq!(client.wakeup_count(), 2);
    }

    #[test]
    fn test_mock_metrics_close() {
        let metrics = MockMetrics::new();
        assert!(!metrics.is_closed());

        metrics.close();
        assert!(metrics.is_closed());
    }

    #[test]
    fn test_mock_coordinator_default() {
        let coordinator = MockWorkerCoordinator::default();
        assert_eq!(coordinator.member_id(), "member-1");
        assert_eq!(coordinator.current_protocol_version(), 1);
        assert!(!coordinator.is_stopped());
    }

    // ===== Cross-crate 接缝验证测试 =====
    // 验证 connect-runtime 可以正确使用 kafka-clients-mock 的 MockWorkerCoordinator

    /// 测试跨 crate WorkerCoordinator 接缝：使用 kafka-clients-mock 的 coordinator
    /// 验证 API 契约与 Java WorkerCoordinator 一致（核心路径：join/sync/leave/poll/rejoin）
    #[test]
    fn test_cross_crate_coordinator_api_contract() {
        use kafka_clients_mock::coordinator::ConnectProtocolCompatibility;
        use kafka_clients_mock::coordinator::MockWorkerCoordinator as KafkaMockCoordinator;

        // 创建跨 crate coordinator
        let coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Compatible,
        );

        // 验证 API 契约一致
        assert_eq!(coordinator.rest_url(), "http://localhost:8083");
        assert_eq!(coordinator.group_id(), "connect-group");
        assert_eq!(coordinator.protocol_type(), "connect");
        assert_eq!(
            coordinator.state(),
            kafka_clients_mock::coordinator::MemberState::Unjoined
        );
        assert_eq!(
            coordinator.generation_id(),
            kafka_clients_mock::coordinator::NO_GENERATION
        );
        assert_eq!(
            coordinator.member_id(),
            kafka_clients_mock::coordinator::UNKNOWN_MEMBER_ID
        );
        assert!(coordinator.coordinator_unknown());
        assert!(coordinator.assignment().is_none());
    }

    /// 测试跨 crate join/sync 流程
    #[test]
    fn test_cross_crate_join_sync_flow() {
        use kafka_clients_mock::coordinator::ConnectProtocolCompatibility;
        use kafka_clients_mock::coordinator::MockWorkerCoordinator as KafkaMockCoordinator;

        let mut coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Compatible,
        );

        // join_group
        let join_result = coordinator.join_group();
        assert!(join_result.is_ok());
        let join_response = join_result.unwrap();
        assert!(join_response.is_leader()); // First member becomes leader
        assert_eq!(
            coordinator.state(),
            kafka_clients_mock::coordinator::MemberState::Syncing
        );

        // sync_group
        let sync_result = coordinator.sync_group();
        assert!(sync_result.is_ok());
        assert_eq!(
            coordinator.state(),
            kafka_clients_mock::coordinator::MemberState::Stable
        );
        assert!(coordinator.assignment().is_some());
    }

    /// 测试跨 crate leave_group 流程
    #[test]
    fn test_cross_crate_leave_group_flow() {
        use kafka_clients_mock::coordinator::ConnectProtocolCompatibility;
        use kafka_clients_mock::coordinator::MockWorkerCoordinator as KafkaMockCoordinator;

        let mut coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Compatible,
        );

        // Join and sync first
        coordinator.join_group().unwrap();
        coordinator.sync_group().unwrap();
        assert_eq!(
            coordinator.state(),
            kafka_clients_mock::coordinator::MemberState::Stable
        );

        // leave_group
        let leave_result = coordinator.leave_group();
        assert!(leave_result.is_ok());
        assert_eq!(
            coordinator.state(),
            kafka_clients_mock::coordinator::MemberState::Unjoined
        );
        assert!(coordinator.assignment().is_none());
        assert_eq!(
            coordinator.generation_id(),
            kafka_clients_mock::coordinator::NO_GENERATION
        );
    }

    /// 测试跨 crate request_rejoin 流程
    #[test]
    fn test_cross_crate_request_rejoin() {
        use kafka_clients_mock::coordinator::ConnectProtocolCompatibility;
        use kafka_clients_mock::coordinator::MockWorkerCoordinator as KafkaMockCoordinator;

        let mut coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Compatible,
        );

        // Ensure active group first
        coordinator.ensure_active_group().unwrap();
        assert!(!coordinator.rejoin_needed_or_pending());

        // Request rejoin
        coordinator.request_rejoin("test reason");
        assert!(coordinator.rejoin_needed_or_pending());
    }

    // ===== 协议不兼容失败路径测试 =====
    // 验证 CONFIG_MISMATCH 触发 rejoin

    /// 测试 CONFIG_MISMATCH assignment 触发 rejoin
    /// Java WorkerCoordinator: when assignment.failed() = true, rejoinNeededOrPending() returns true
    #[test]
    fn test_config_mismatch_triggers_rejoin() {
        use kafka_clients_mock::coordinator::MockWorkerCoordinator as KafkaMockCoordinator;
        use kafka_clients_mock::coordinator::{ConnectProtocolCompatibility, ExtendedAssignment};

        let mut coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Compatible,
        );

        // Join and sync to get stable assignment
        coordinator.join_group().unwrap();
        coordinator.sync_group().unwrap();
        assert_eq!(
            coordinator.state(),
            kafka_clients_mock::coordinator::MemberState::Stable
        );

        // Set a failed assignment (CONFIG_MISMATCH)
        let failed_assignment = ExtendedAssignment::new(
            ExtendedAssignment::CONNECT_PROTOCOL_V1,
            ExtendedAssignment::CONFIG_MISMATCH, // Error code 1 = CONFIG_MISMATCH
            Some("leader".to_string()),
            Some("http://leader:8083".to_string()),
            100,
            vec![], // No connectors assigned
            vec![], // No tasks assigned
            vec![], // No revoked connectors
            vec![], // No revoked tasks
            0,
        );

        coordinator.set_assignment(failed_assignment);

        // Verify: failed assignment triggers rejoinNeededOrPending()
        assert!(coordinator.assignment().unwrap().failed());
        assert!(
            coordinator.rejoin_needed_or_pending(),
            "CONFIG_MISMATCH should trigger rejoin"
        );
    }

    /// 测试协议不兼容时触发 rejoin 和错误恢复
    /// Java: when protocol version mismatch, coordinator should requestRejoin()
    #[test]
    fn test_protocol_incompatibility_recovery() {
        use kafka_clients_mock::coordinator::MockWorkerCoordinator as KafkaMockCoordinator;
        use kafka_clients_mock::coordinator::{
            ConnectProtocolCompatibility, ExtendedAssignment, LeaderState,
        };
        use std::collections::HashMap;

        let mut coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Sessioned, // Start with V2
        );

        // Join and sync
        coordinator.join_group().unwrap();
        coordinator.sync_group().unwrap();
        assert_eq!(coordinator.current_protocol_version(), 2); // V2

        // Simulate protocol downgrade scenario: leader selects V1 (Compatible)
        // In Java, this would happen when leader's protocol selection differs
        let v1_assignment = ExtendedAssignment::new(
            1, // V1 protocol version
            ExtendedAssignment::NO_ERROR,
            Some("leader".to_string()),
            Some("http://leader:8083".to_string()),
            100,
            vec!["connector-a".to_string()],
            vec![],
            vec![],
            vec![],
            0,
        );

        coordinator.set_assignment(v1_assignment.clone());

        // After receiving V1 assignment, worker should update protocol version
        // Note: In Java, this happens in onJoinComplete()
        assert_eq!(coordinator.assignment().unwrap().version(), 1);
        assert!(!coordinator.assignment().unwrap().failed());

        // If assignment indicates protocol mismatch (error = CONFIG_MISMATCH),
        // worker should request rejoin
        let mismatch_assignment = ExtendedAssignment::new(
            1,
            ExtendedAssignment::CONFIG_MISMATCH,
            Some("leader".to_string()),
            Some("http://leader:8083".to_string()),
            -1, // Invalid offset indicates config mismatch
            vec![],
            vec![],
            vec![],
            vec![],
            0,
        );

        coordinator.set_assignment(mismatch_assignment);

        // CONFIG_MISMATCH assignment should trigger rejoin
        assert!(coordinator.assignment().unwrap().failed());
        assert!(coordinator.rejoin_needed_or_pending());

        // Recovery: ensure active group should work
        let recovery_result = coordinator.ensure_active_group();
        assert!(
            recovery_result.is_ok(),
            "Coordinator should recover by rejoining"
        );
    }

    /// 测试 assignment snapshot 与 leader state 一致性
    /// Java WorkerCoordinator: assignmentSnapshot tracks current assignment state
    #[test]
    fn test_assignment_snapshot_consistency() {
        use kafka_clients_mock::coordinator::MockWorkerCoordinator as KafkaMockCoordinator;
        use kafka_clients_mock::coordinator::{ConnectProtocolCompatibility, ExtendedAssignment};

        let mut coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Compatible,
        );

        // Initial state: no assignment
        assert!(coordinator.assignment().is_none());
        assert!(
            coordinator.last_completed_generation_id()
                == kafka_clients_mock::coordinator::NO_GENERATION
        );

        // After join/sync: should have assignment
        coordinator.ensure_active_group().unwrap();
        assert!(coordinator.assignment().is_some());
        assert!(coordinator.last_completed_generation_id() >= 1);

        // Assignment snapshot should reflect current state
        let assignment = coordinator.assignment().unwrap();
        assert_eq!(assignment.error(), ExtendedAssignment::NO_ERROR);
        assert!(!assignment.failed());
    }

    /// 测试 poll heartbeat 和 rejoin 逻辑
    /// Java WorkerCoordinator.poll(): checks coordinatorUnknown, rejoinNeededOrPending, then heartbeat
    #[test]
    fn test_poll_with_rejoin_needed() {
        use kafka_clients_mock::coordinator::ConnectProtocolCompatibility;
        use kafka_clients_mock::coordinator::MockWorkerCoordinator as KafkaMockCoordinator;

        let mut coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Compatible,
        );

        // Poll when coordinator unknown should fail
        let poll_result = coordinator.poll(1000);
        assert!(
            poll_result.is_err(),
            "Poll should fail when coordinator unknown"
        );

        // Ensure active group first
        coordinator.ensure_active_group().unwrap();

        // Poll should succeed when stable
        let poll_result = coordinator.poll(1000);
        assert!(poll_result.is_ok(), "Poll should succeed when stable");

        // Request rejoin
        coordinator.request_rejoin("test poll rejoin");
        assert!(coordinator.rejoin_needed_or_pending());

        // Poll with rejoin needed should trigger ensure_active_group internally
        let poll_result = coordinator.poll(100);
        assert!(
            poll_result.is_ok(),
            "Poll should handle rejoin automatically"
        );
        assert!(
            !coordinator.rejoin_needed_or_pending(),
            "Rejoin should be completed"
        );
    }

    /// 测试 owner URL 查询（leader state 功能）
    /// Java WorkerCoordinator: leader can query owner URLs for connectors/tasks
    #[test]
    fn test_leader_state_owner_url_queries() {
        use kafka_clients_mock::coordinator::{
            ConnectProtocolCompatibility, ConnectorTaskId, LeaderState,
            MockWorkerCoordinator as KafkaMockCoordinator,
        };
        use std::collections::HashMap;

        let mut coordinator = KafkaMockCoordinator::new(
            "http://localhost:8083".to_string(),
            "connect-group".to_string(),
            ConnectProtocolCompatibility::Compatible,
        );

        // Set up as leader with leader state
        coordinator.ensure_active_group().unwrap();
        assert!(coordinator.is_leader());

        // Create leader state with assignments
        let all_members = HashMap::new();
        let mut connector_assignment = HashMap::new();
        connector_assignment.insert("worker-1".to_string(), vec!["conn-1".to_string()]);

        let mut task_assignment = HashMap::new();
        task_assignment.insert(
            "worker-1".to_string(),
            vec![ConnectorTaskId::new("conn-1".to_string(), 0)],
        );

        let leader_state = LeaderState::new(all_members, connector_assignment, task_assignment);
        coordinator.set_leader_state(Some(leader_state));

        // Query owner URLs
        let owner_url = coordinator.owner_url_for_connector("conn-1");
        // Note: owner URL depends on all_members state
        // In mock, if no members have URLs, returns None

        let task_owner_url =
            coordinator.owner_url_for_task(&ConnectorTaskId::new("conn-1".to_string(), 0));
        // Same logic applies for task queries
    }
}
